package: hermes-studio

application:
  subdomain: hermes-studio
  privileged: true
  upstreams:
    - location: /
      backend: http://hermes-webui:{{ .U.port }}/
    - location: /preview/
      backend: http://hermes-webui:{{ .U.preview_frontend_port }}/
      disable_auto_health_checking: true
    - location: /xai-oauth/
      backend: http://hermes-webui:{{ .U.xai_oauth_port }}/
      disable_auto_health_checking: true

  public_path:
    - /

services:
  hermes-webui:
    image: embed:hermes-studio
    setup_script: /opt/setup-once.sh
    environment:
      - PORT={{ .U.port }}
      - HERMES_HOME=/home/agent/.hermes
      - HERMES_BIN=/opt/hermes/.venv/bin/hermes
      - HERMES_WEB_UI_MANAGED_GATEWAY=1
      - HERMES_WEB_UI_XAI_CALLBACK_BIND_HOST=0.0.0.0
      - PATH=/home/agent/.local/bin:/opt/hermes/.venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - HERMES_ALLOW_ROOT_GATEWAY=1
    binds:
      - /lzcapp/var/home:/home/agent
      - /var/run/docker.sock:/var/run/docker.sock
